version: "3"
services:
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: build/Dockerfile
    volumes:
      - ./:/src
    tty: true
    working_dir: /src
    command: /bin/bash