version: "3"
services:
  go_practice:
    container_name: "go_practice"
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/go/src/go_practice
    tty: true
    ports:
      - 3000:3000
